CREATE TABLE todo (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	todo TEXT NOT NULL,
	completed CHAR(1) DEFAULT 0,
	updated_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
 	created_date TIMESTAMP DEFAULT 0
)
